//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositorioTiendaBF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompraProducto
    {
        public int idCompra { get; set; }
        public int idProducto { get; set; }
        public int Unidades { get; set; }
        public decimal SubTotal { get; set; }
    
        public virtual Compra Compra { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
